# Generated by Django 5.0.1 on 2024-01-02 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeskModuleType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("module_type", models.CharField(max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="DeskModule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=150)),
                ("icon", models.CharField(max_length=20)),
                ("description", models.TextField(blank=True, null=True)),
                ("list_definition_id", models.IntegerField(blank=True, null=True)),
                ("form_id", models.IntegerField(blank=True, null=True)),
                ("external_url", models.URLField(blank=True, null=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "parent_module_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="desk_modules.deskmodule",
                    ),
                ),
                (
                    "module_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="desk_modules.deskmoduletype"),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="deskmodule",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("external_url__isnull", True), ("form_id__isnull", True), ("list_definition_id__isnull", True)
                    ),
                    models.Q(
                        ("external_url__isnull", True),
                        ("form_id__isnull", True),
                        ("list_definition_id__isnull", False),
                    ),
                    models.Q(
                        ("external_url__isnull", True),
                        ("form_id__isnull", False),
                        ("list_definition_id__isnull", True),
                    ),
                    models.Q(
                        ("external_url__isnull", False),
                        ("form_id__isnull", True),
                        ("list_definition_id__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="check a maximum of one endpoint option is filled in",
            ),
        ),
    ]
