# Generated by Django 5.0 on 2023-12-25 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeskModuleType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("module_type", models.CharField(max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="DeskModule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField()),
                ("url", models.URLField()),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "parent_module_id",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="desk_modules.deskmodule"
                    ),
                ),
                (
                    "module_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="desk_modules.deskmoduletype"),
                ),
            ],
        ),
    ]
